In [1]:
import numpy as np

**Standard Python Lists Versus Arrays**

So why would we want to use a numbpy array over a list?  You can loop over both

In [3]:
pythonList = [1, 2, 3]
numpyArray = np.array([1, 2, 3])
for e in pythonList:
    print(e)
    
for e in numpyArray:
    print(e)

1
2
3
1
2
3


Some methods, like append, from standard lists can't be used by numpy arrays. You can't add things together like + too.  Sounds like  numpy is more like R, which I like! For example, addition is NOT append, but pointwise/elementwise addition. 

In [4]:
print(numpyArray + numpyArray)

[2 4 6]


In [5]:
#just makes a new list...boo
print(pythonList + pythonList)

[1, 2, 3, 1, 2, 3]


You can also multiple like in R. If you wanted to do this for a list, you'd need to use a loop (boo):

In [8]:
print(2*numpyArray)
# a list just concatenates
print(2*pythonList)

[2 4 6]
[1, 2, 3, 1, 2, 3]


In [ ]:
You use ** for power in python and can do this on numpy arrays too (the ^ does not work):

In [12]:
print(numpyArray**2)

array([1, 4, 9])

The square root also works in numpy, but you do it via a function:

In [11]:
print(np.sqrt(numpyArray))

array([ 1.        ,  1.41421356,  1.73205081])

In [14]:
#try log too
print(np.log(numpyArray))
#exponential
print(np.exp(numpyArray))

[ 0.          0.69314718  1.09861229]
[  2.71828183   7.3890561   20.08553692]


**Dot products in numpy**

Remember that there are two definitions, but they're the same:
- scalar pointwise multiplication $$a \cdot b = a^{T}b = \sum^{D}_{d=1}a_{d}b_{d}$$
- geometric interpreation using scalars and cosine: not useful as much? like when calculating the angle between two planes. $$a \cdot b = |a| |b|cos(\theta)_{ab}$$

So like in R, a numpy array is like a mathematical vector. Let's assume a and b are nx1 vectors for simplicity.

In [18]:
#start out with two vectors
a = np.array([1,2])
b = np.array([2, 1])

Let's hand-compute the dot product as a refresher - multiply the elements of row $d$ of a for each column of b, and sum these up.  

Use the "zip" function to basically make a 2d array you step through row by row. 

In [20]:
#must initialize dot
dot = 0
for e, f in zip(a, b):
    dot += e*f

print(dot)

4


As expected, in  numpy we can just use the \* symbol. That's nice - remember how in R you kept forgetting to use %*% for matrix multiplication?

As expected, in  numpy we can just use the * symbol. That's nice - remember how in R you kept forgetting to use *% for matrix multiplication

Now remember that the dot product isn't equatable to multiplying two matrices - the dot product is the SUM of the matrix that resulted from multiplying two matrices together.

Remeber that to get each new row in the "output" for matrix multiplication, you multiply the elements of a in row $d$ of a for each column of b, and sum these up.  In numpy, just use the * symbol to do this multiplication:

In [26]:
a*b

array([2, 2])

To get the dot product, you'd sum up this "output" multiplication matrix. Note that you need to use the sum() function:

In [27]:
np.sum(a*b)

4

Something interesting - you can also do it the way below, because sum is a method for your numpy instance (in this case, the numpy instance is the result of a*b). I think the latter method is clearer and more like object-oriented languages.

In [28]:
(a*b).sum()

4

There is also a dot function to do it in one fellow swoop:

In [30]:
np.dot(a,b)
a.dot(b)
b.dot(a)

4

Let's try calculating the dot product through the geometric interpretation - remember  $$a \cdot b = |a| |b|cos(\theta)_{ab}$$

Our first step is to get the magnitudes $$|a|$$ and $$|b|$$